In [2]:
pip install pandas

Collecting pandas
  Downloading pandas-3.0.6-cp311-cp311-win_amd64.whl (9.9 MB)
     ---------------------------------------- 9.9/9.9 MB 154.2 kB/s eta 0:00:00
Collecting numpy>=1.26.0
  Downloading numpy-2.4.6-cp311-cp311-win_amd64.whl (12.6 MB)
     -------------------------------------- 12.6/12.6 MB 136.2 kB/s eta 0:00:00
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\admin\appdata\roaming\python\python311\site-packages (from pandas) (2.9.0.post0)
Collecting tzdata
  Downloading tzdata-2026.5-py2.py3-none-any.whl (347 kB)
     ------------------------------------ 348.0/348.0 kB 214.0 kB/s eta 0:00:00
Requirement already satisfied: six>=1.5 in c:\users\admin\appdata\roaming\python\python311\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Installing collected packages: tzdata, numpy, pandas
Successfully installed numpy-2.4.6 pandas-3.0.6 tzdata-2026.5
Note: you may need to restart the kernel to use updated packages.

  WARNING: The scripts f2py.exe and numpy-config.exe are installed in 'c:\Users\Admin\AppData\Local\Programs\Python\Python311\Scripts' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.

[notice] A new release of pip available: 22.3 -> 26.2.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [3]:
import pandas as pd

In [13]:
df = pd.read_csv("retail_sales.csv.csv")

In [14]:
df.head()

,YEAR,MONTH,SUPPLIER,ITEM CODE,ITEM DESCRIPTION,ITEM TYPE,RETAIL SALES,RETAIL TRANSFERS,WAREHOUSE SALES
0,2020,1,REPUBLIC NATIONAL DISTRIBUTING CO,100009,BOOTLEG RED - 750ML,WINE,0.00,0.0,2.0
1,2020,1,PWSWN INC,100024,MOMENT DE PLAISIR - 750ML,WINE,0.00,1.0,4.0
2,2020,1,RELIABLE CHURCHILL LLLP,1001,S SMITH ORGANIC PEAR CIDER - 18.7OZ,BEER,0.00,0.0,1.0
3,2020,1,LANTERNA DISTRIBUTORS INC,100145,SCHLINK HAUS KABINETT - 750ML,WINE,0.00,0.0,1.0
4,2020,1,DIONYSOS IMPORTS INC,100293,SANTORINI GAVALA WHITE - 750ML,WINE,0.82,0.0,0.0

In [15]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 30000 entries, 0 to 29999
Data columns (total 9 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   YEAR              30000 non-null  int64
 1   MONTH             30000 non-null  int64
 2   SUPPLIER          29967 non-null  str
 3   ITEM CODE         30000 non-null  str
 4   ITEM DESCRIPTION  30000 non-null  str
 5   ITEM TYPE         30000 non-null  str
 6   RETAIL SALES      29999 non-null  float64
 7   RETAIL TRANSFERS  30000 non-null  float64
 8   WAREHOUSE SALES   30000 non-null  float64
dtypes: float64(3), int64(2), str(4)
memory usage: 2.1 MB

In [16]:
df.describe()

          YEAR         MONTH  RETAIL SALES  RETAIL TRANSFERS  WAREHOUSE SALES
count  30000.0  30000.000000  29999.000000      30000.000000     30000.000000
mean    2020.0      3.911467      6.939796          6.594058        27.431031
std        0.0      2.836788     33.081054         27.879428       272.166085
min     2020.0      1.000000     -0.420000         -6.000000     -3999.000000
25%     2020.0      1.000000      0.000000          0.000000         0.000000
50%     2020.0      3.000000      0.160000          0.000000         1.000000
75%     2020.0      7.000000      2.920000          3.000000         6.000000
max     2020.0      9.000000   2739.000000       1507.000000     18317.000000

In [17]:
df.columns

Index(['YEAR', 'MONTH', 'SUPPLIER', 'ITEM CODE', 'ITEM DESCRIPTION',
       'ITEM TYPE', 'RETAIL SALES', 'RETAIL TRANSFERS', 'WAREHOUSE SALES'],
      dtype='str')

In [18]:
df.isnull().sum()

YEAR                 0
MONTH                0
SUPPLIER            33
ITEM CODE            0
ITEM DESCRIPTION     0
ITEM TYPE            0
RETAIL SALES         1
RETAIL TRANSFERS     0
WAREHOUSE SALES      0
dtype: int64

In [19]:
df["SUPPLIER"] = df["SUPPLIER"].fillna("Unknown")

In [20]:
df["RETAIL SALES"] = df["RETAIL SALES"].fillna(0)

In [21]:
df.isnull().sum()

YEAR                0
MONTH               0
SUPPLIER            0
ITEM CODE           0
ITEM DESCRIPTION    0
ITEM TYPE           0
RETAIL SALES        0
RETAIL TRANSFERS    0
WAREHOUSE SALES     0
dtype: int64

In [22]:
df.groupby("ITEM TYPE")["RETAIL SALES"].sum()

ITEM TYPE
BEER            59538.76
DUNNAGE             0.00
KEGS                0.00
LIQUOR          81742.85
NON-ALCOHOL      6824.62
REF                46.27
STR_SUPPLIES      345.60
WINE            59688.84
Name: RETAIL SALES, dtype: float64

In [23]:
df.groupby("ITEM TYPE")["RETAIL SALES"].mean()

ITEM TYPE
BEER            14.118748
DUNNAGE          0.000000
KEGS             0.000000
LIQUOR          13.635171
NON-ALCOHOL     31.595463
REF              5.783750
STR_SUPPLIES     5.485714
WINE             3.195334
Name: RETAIL SALES, dtype: float64

In [24]:
df["RETAIL SALES"] = df["RETAIL SALES"].fillna(df["RETAIL SALES"].median())

In [25]:
df["SUPPLIER"] = df["SUPPLIER"].fillna(df["SUPPLIER"].mode()[0])

In [26]:
df.isnull().sum()

YEAR                0
MONTH               0
SUPPLIER            0
ITEM CODE           0
ITEM DESCRIPTION    0
ITEM TYPE           0
RETAIL SALES        0
RETAIL TRANSFERS    0
WAREHOUSE SALES     0
dtype: int64

In [27]:
df.head(10)

,YEAR,MONTH,SUPPLIER,ITEM CODE,ITEM DESCRIPTION,ITEM TYPE,RETAIL SALES,RETAIL TRANSFERS,WAREHOUSE SALES
0,2020,1,REPUBLIC NATIONAL DISTRIBUTING CO,100009,BOOTLEG RED - 750ML,WINE,0.00,0.0,2.0
1,2020,1,PWSWN INC,100024,MOMENT DE PLAISIR - 750ML,WINE,0.00,1.0,4.0
2,2020,1,RELIABLE CHURCHILL LLLP,1001,S SMITH ORGANIC PEAR CIDER - 18.7OZ,BEER,0.00,0.0,1.0
3,2020,1,LANTERNA DISTRIBUTORS INC,100145,SCHLINK HAUS KABINETT - 750ML,WINE,0.00,0.0,1.0
4,2020,1,DIONYSOS IMPORTS INC,100293,SANTORINI GAVALA WHITE - 750ML,WINE,0.82,0.0,0.0
5,2020,1,KYSELA PERE ET FILS LTD,100641,CORTENOVA VENETO P/GRIG - 750ML,WINE,2.76,0.0,6.0
6,2020,1,SANTA MARGHERITA USA INC,100749,SANTA MARGHERITA P/GRIG ALTO - 375ML,WINE,0.08,1.0,1.0
7,2020,1,BROWN-FORMAN BEVERAGES WORLDWIDE,1008,JACK DANIELS COUNTRY COCKTAIL SOUTHERN PEACH -...,BEER,0.00,0.0,2.0
8,2020,1,JIM BEAM BRANDS CO,10103,KNOB CREEK BOURBON 9YR - 100P - 375ML,LIQUOR,6.41,4.0,0.0
9,2020,1,INTERNATIONAL CELLARS LLC,101117,KSARA CAB - 750ML,WINE,0.33,1.0,2.0

In [28]:
df.isnull().sum()

YEAR                0
MONTH               0
SUPPLIER            0
ITEM CODE           0
ITEM DESCRIPTION    0
ITEM TYPE           0
RETAIL SALES        0
RETAIL TRANSFERS    0
WAREHOUSE SALES     0
dtype: int64

In [29]:
df.to_csv("retail_sales_cleaned.csv", index=False)